pipeline {
	agent {
		node {
			label 'Api'
		}
	}
	tools {
        jdk 'JDK11'
    }


	stages {
		stage ('Api Tests') {
            steps {
                sh '''
                mvn clean test
                '''
            }
        }
	}

	post {
        always {
            script {
            	sh '''
                    echo 'execute post build'
                    cp ApiTests/src/test/resources/environment.properties ApiTests/target/allure-results/environment.properties
                    '''
            }
            cleanWs()
        }
    }
}
