pipeline {
	agent any
	tools {
	    maven 'maven jenkins'
	    allure 'allure'
        jdk 'JDK_11'
    }

	stages {
	    stage ('Build') {
                steps {
                    sh '''
                    cd ApiTests
                    mvn clean compile
                    '''
                }
            }
		stage ('Api Tests') {
            steps {
                sh '''
                cd ApiTests
                mvn test
                '''
            }
        }
	}

	post {
	    always {
                        steps {
                           allure([
                      	   includeProperties: false,
                      	   jdk: '',
                      	   properties: [],
                      	   reportBuildPolicy: 'ALWAYS',
                      	   results: [[path: 'ApiTests/target/allure-results']]
                    	   ])
                  	        }
	}
	}
}
