pipeline {
	agent any
	tools {
	    maven 'maven jenkins'
        jdk 'JDK_11'
    }


	stages {
	    stage ('Build') {
                steps {
                    sh '''
                    cd ApiTests
                    mvn clean compile
                    '''
                }
            }
		stage ('Api Tests') {
            steps {
                sh '''
                cd ApiTests
                mvn test
                '''
            }
        }
	}

	post {
        always {
            script {
            	sh '''
                    echo 'execute post build'
                    cp ApiTests/src/test/resources/environment.properties ApiTests/target/allure-results/
                    allure serve
                    '''
            }
            cleanWs()
        }
    }
}
